package cn.mirrorming.spring.cloud.alibaba.consumer.entity;

import java.io.Serializable;
import java.util.Date;

public class archiveManage implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column archive_manage.id
     *
     * @mbg.generated Mon Nov 23 10:09:50 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column archive_manage.project_id
     *
     * @mbg.generated Mon Nov 23 10:09:50 CST 2020
     */
    private Long projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column archive_manage.publish_time
     *
     * @mbg.generated Mon Nov 23 10:09:50 CST 2020
     */
    private Date publishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column archive_manage.archive_type
     *
     * @mbg.generated Mon Nov 23 10:09:50 CST 2020
     */
    private String archiveType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column archive_manage.archive_summary
     *
     * @mbg.generated Mon Nov 23 10:09:50 CST 2020
     */
    private String archiveSummary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column archive_manage.create_time
     *
     * @mbg.generated Mon Nov 23 10:09:50 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column archive_manage.update_time
     *
     * @mbg.generated Mon Nov 23 10:09:50 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column archive_manage.creator_id
     *
     * @mbg.generated Mon Nov 23 10:09:50 CST 2020
     */
    private Long creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column archive_manage.updater_id
     *
     * @mbg.generated Mon Nov 23 10:09:50 CST 2020
     */
    private Long updaterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column archive_manage.is_removed
     *
     * @mbg.generated Mon Nov 23 10:09:50 CST 2020
     */
    private Byte isRemoved;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table archive_manage
     *
     * @mbg.generated Mon Nov 23 10:09:50 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column archive_manage.id
     *
     * @return the value of archive_manage.id
     *
     * @mbg.generated Mon Nov 23 10:09:50 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column archive_manage.id
     *
     * @param id the value for archive_manage.id
     *
     * @mbg.generated Mon Nov 23 10:09:50 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column archive_manage.project_id
     *
     * @return the value of archive_manage.project_id
     *
     * @mbg.generated Mon Nov 23 10:09:50 CST 2020
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column archive_manage.project_id
     *
     * @param projectId the value for archive_manage.project_id
     *
     * @mbg.generated Mon Nov 23 10:09:50 CST 2020
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column archive_manage.publish_time
     *
     * @return the value of archive_manage.publish_time
     *
     * @mbg.generated Mon Nov 23 10:09:50 CST 2020
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column archive_manage.publish_time
     *
     * @param publishTime the value for archive_manage.publish_time
     *
     * @mbg.generated Mon Nov 23 10:09:50 CST 2020
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column archive_manage.archive_type
     *
     * @return the value of archive_manage.archive_type
     *
     * @mbg.generated Mon Nov 23 10:09:50 CST 2020
     */
    public String getArchiveType() {
        return archiveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column archive_manage.archive_type
     *
     * @param archiveType the value for archive_manage.archive_type
     *
     * @mbg.generated Mon Nov 23 10:09:50 CST 2020
     */
    public void setArchiveType(String archiveType) {
        this.archiveType = archiveType == null ? null : archiveType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column archive_manage.archive_summary
     *
     * @return the value of archive_manage.archive_summary
     *
     * @mbg.generated Mon Nov 23 10:09:50 CST 2020
     */
    public String getArchiveSummary() {
        return archiveSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column archive_manage.archive_summary
     *
     * @param archiveSummary the value for archive_manage.archive_summary
     *
     * @mbg.generated Mon Nov 23 10:09:50 CST 2020
     */
    public void setArchiveSummary(String archiveSummary) {
        this.archiveSummary = archiveSummary == null ? null : archiveSummary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column archive_manage.create_time
     *
     * @return the value of archive_manage.create_time
     *
     * @mbg.generated Mon Nov 23 10:09:50 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column archive_manage.create_time
     *
     * @param createTime the value for archive_manage.create_time
     *
     * @mbg.generated Mon Nov 23 10:09:50 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column archive_manage.update_time
     *
     * @return the value of archive_manage.update_time
     *
     * @mbg.generated Mon Nov 23 10:09:50 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column archive_manage.update_time
     *
     * @param updateTime the value for archive_manage.update_time
     *
     * @mbg.generated Mon Nov 23 10:09:50 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column archive_manage.creator_id
     *
     * @return the value of archive_manage.creator_id
     *
     * @mbg.generated Mon Nov 23 10:09:50 CST 2020
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column archive_manage.creator_id
     *
     * @param creatorId the value for archive_manage.creator_id
     *
     * @mbg.generated Mon Nov 23 10:09:50 CST 2020
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column archive_manage.updater_id
     *
     * @return the value of archive_manage.updater_id
     *
     * @mbg.generated Mon Nov 23 10:09:50 CST 2020
     */
    public Long getUpdaterId() {
        return updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column archive_manage.updater_id
     *
     * @param updaterId the value for archive_manage.updater_id
     *
     * @mbg.generated Mon Nov 23 10:09:50 CST 2020
     */
    public void setUpdaterId(Long updaterId) {
        this.updaterId = updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column archive_manage.is_removed
     *
     * @return the value of archive_manage.is_removed
     *
     * @mbg.generated Mon Nov 23 10:09:50 CST 2020
     */
    public Byte getIsRemoved() {
        return isRemoved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column archive_manage.is_removed
     *
     * @param isRemoved the value for archive_manage.is_removed
     *
     * @mbg.generated Mon Nov 23 10:09:50 CST 2020
     */
    public void setIsRemoved(Byte isRemoved) {
        this.isRemoved = isRemoved;
    }
}