package cn.mirrorming.spring.cloud.alibaba.consumer.dao;

import cn.mirrorming.spring.cloud.alibaba.consumer.entity.archiveManage;

public interface archiveManageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archive_manage
     *
     * @mbg.generated Mon Nov 23 10:09:50 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archive_manage
     *
     * @mbg.generated Mon Nov 23 10:09:50 CST 2020
     */
    int insert(archiveManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archive_manage
     *
     * @mbg.generated Mon Nov 23 10:09:50 CST 2020
     */
    int insertSelective(archiveManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archive_manage
     *
     * @mbg.generated Mon Nov 23 10:09:50 CST 2020
     */
    archiveManage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archive_manage
     *
     * @mbg.generated Mon Nov 23 10:09:50 CST 2020
     */
    int updateByPrimaryKeySelective(archiveManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archive_manage
     *
     * @mbg.generated Mon Nov 23 10:09:50 CST 2020
     */
    int updateByPrimaryKey(archiveManage record);
}